# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NewPaptor
                                 A QGIS plugin
 Add a new Raptor nest, create buffer and impact table
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-16
        copyright            : (C) 2021 by Setare
        email                : setare@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NewPaptor class from file NewPaptor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .new_raptor import NewPaptor
    return NewPaptor(iface)
